### ISSUE TITLE
Error in plugin 'sass'

### ISSUE THREAD

**Issue by murilotimo** [liip-elearning/moodle-theme-template#2]
Hi,

when I use gulp
I receive the following error message:

Error in plugin 'sass'
Message:
    ..\boost\scss\moodle\forms.scss
Error: expected a string constant or identifier in attribute selector for size
        on line 329 of ../boost/scss/moodle/forms.scss
>> select[size=1] {
   -----------^

Did I make a mistake?

**Comment by OdyX** [comment]
Indeed. That's a Moodle bug: https://tracker.moodle.org/browse/MDL-58610 . Our fix is easy:

```
Author: Raphaël Santos <raphael.santos@liip.ch>
Date:   Sun Jun 4 10:09:22 2017 +0200

    Fix sass selector in theme_boost
    
    Bug in libsass causes a compilation error if value is not a string.
    This is not happening with the Moodle libsass but with the frontend stack used by Liip's custom themes.

diff --git a/theme/boost/scss/moodle/forms.scss b/theme/boost/scss/moodle/forms.scss
index a23abd8aeb4..c6316cf63ea 100644
--- a/theme/boost/scss/moodle/forms.scss
+++ b/theme/boost/scss/moodle/forms.scss
@@ -326,7 +326,7 @@ select[size],
 select[multiple] {
     overflow: auto;
 }
-select[size=1] {
+select[size="1"] {
     overflow: visible;
 }
 ```

**Comment by scara** [comment]
Hi @OdyX,
would you mind to create a Moodle branch for your fix?
Refs:
- https://docs.moodle.org/dev/Process#Develop_your_change_using_git
- https://docs.moodle.org/dev/Git_for_developers#Preparing_a_patch

TIA,
Matteo

**Comment by ragusa87** [comment]
This bug has been fixed by Moodle HQ a long time ago. I am closing the issue.
